image: jkube/maven:15-alpine

pipelines:
  default:
    - step:
        name: Docker image for branch
        services:
          - docker
        script:
          - docker-build $DOCKER_HUB_PASSWORD $BITBUCKET_BRANCH
  tags:
    '**':
      - step:
          name: Docker image for tag
          services:
            - docker
          script:
            - sed -i "s~<properties>~<properties><docker.repo.password>$DOCKER_HUB_PASSWORD</docker.repo.password>~" pom.xml
            - mvn -B package -Dgit.branch=$BITBUCKET_TAG
