#!/bin/sh
# copy masterkey in file (which can be deleted after reading)
echo $GITBEAVER_MASTERKEY > /masterkey
# clear masterkey environment variable such that it cannot leak out
export GITBEAVER_MASTERKEY=deleted
java -cp /main.jar:/lib/*:plugins org.jkube.gitbeaver.Main $@
EXITCODE=$?
if test $EXITCODE -ne 0
then
  echo Gitbeaver returned exit code $EXITCODE
  exit $EXITCODE
else
  echo Gitbeaver terminated normally
fi