#!/bin/sh
echo $GITBEAVER_MASTERKEY > /masterkey
export $GITBEAVER_MASTERKEY=deleted
java -cp main.jar:plugins --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED org.jkube.gitbeaver.Main $@
EXITCODE=$?
if test $EXITCODE -ne 0
then
  echo Gitbeaver returned exit code $EXITCODE
  exit $EXITCODE
else
  echo Gitbeaver terminated normally
fi