name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Build the jar file
      run:  mvn -B package
    - name:  Build and push docker image
      shell: bash
      run: |
            echo TAG=`grep "^    <version>.*</version>$" pom.xml | sed "s# *<[^>]*>##g"`
            echo Docker Image will get tag $TAG
            docker build . -t gitbeaver/core:$TAG
            docker login -u gitbeaver -p ${{ secrets.GITBEAVER_PUSH_TOKEN }}
            docker push gitbeaver/core:$TAG
