name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Build the jar file
      run:  mvn -B package
    - name: Get docker tag
      run: TAG=$GITHUB_HEAD_REF-`grep "<version>.*</version>" pom.xml | sed "s#<.*version>##g"` && echo DockerImageTag=$TAG
    - name:  Build docker image
      run: docker build . -t gitbeaver/core:main
    - name:  Docker login
      run: docker login -u gitbeaver -p ${{ secrets.GITBEAVER_PUSH_TOKEN }}
    - name:  Push docker image
      run: docker push gitbeaver/core:main
