name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Build the jar file
      run:  mvn -B package -Dgit.branch=$BITBUCKET_BRANCH
    - name:  List
      run: ls -rl
    - name:  Build docker image
      run: docker build . -t gitbeaver/core
